// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCT2pogdWg6IFyaP_qXFBrGHtSouASqn2w',
    appId: '1:420160848967:web:0421dc281307532c395d62',
    messagingSenderId: '420160848967',
    projectId: 'flutter-notifications-30b92',
    authDomain: 'flutter-notifications-30b92.firebaseapp.com',
    storageBucket: 'flutter-notifications-30b92.appspot.com',
    measurementId: 'G-W4MNRZTVMZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIbIYnJQa2LbE2dt1qsQrDK1U8lspLiYo',
    appId: '1:420160848967:android:766b991f03d0722c395d62',
    messagingSenderId: '420160848967',
    projectId: 'flutter-notifications-30b92',
    storageBucket: 'flutter-notifications-30b92.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCK5RGRBwAnWh4haIPm3QsPnqv9EKg2BSc',
    appId: '1:420160848967:ios:a05f59bc051e56b1395d62',
    messagingSenderId: '420160848967',
    projectId: 'flutter-notifications-30b92',
    storageBucket: 'flutter-notifications-30b92.appspot.com',
    iosBundleId: 'com.celestezavala.notificaciones',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCK5RGRBwAnWh4haIPm3QsPnqv9EKg2BSc',
    appId: '1:420160848967:ios:ec981986f614d087395d62',
    messagingSenderId: '420160848967',
    projectId: 'flutter-notifications-30b92',
    storageBucket: 'flutter-notifications-30b92.appspot.com',
    iosBundleId: 'com.celestezavala.notificaciones.RunnerTests',
  );
}
